In [10]:
import numpy as np

# 1D tensor (vector)
a1 = np.array([1, 2, 3])

# 2D tensor (matrix)
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])

# 3D tensor
a3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(a1.shape, a2.shape, a3.shape)


(3,) (2, 3) (2, 2, 2)


In [11]:
import torch

t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([[1, 2, 3],
                   [4, 5, 6]])
t3 = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(t1.shape, t2.shape, t3.shape)


torch.Size([3]) torch.Size([2, 3]) torch.Size([2, 2, 2])


In [12]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y)
print(x - y)
print(x * y)
print(x / y)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [13]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

print(x + y)
print(x - y)
print(x * y)
print(x / y)


tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor([0.2500, 0.4000, 0.5000])


In [14]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.dot(a, b))


32


In [15]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print(torch.dot(a, b))


tensor(32)


In [16]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print(A @ B)


[[19 22]
 [43 50]]


In [17]:
A = torch.tensor([[1, 2],
                  [3, 4]])
B = torch.tensor([[5, 6],
                  [7, 8]])

print(torch.matmul(A, B))


tensor([[19, 22],
        [43, 50]])


In [18]:
t = torch.tensor([[10, 20, 30],
                  [40, 50, 60]])

print(t[0])       # First row
print(t[:, 1])    # Second column


tensor([10, 20, 30])
tensor([20, 50])


In [19]:
t = torch.tensor([10, 25, 30, 5])

mask = t > 20
print(mask)
print(t[mask])


tensor([False,  True,  True, False])
tensor([25, 30])


In [20]:
t = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

sub = t[0:2, 1:3]
print(sub)


tensor([[2, 3],
        [5, 6]])


In [21]:
t = torch.arange(6)
print(t.view(2, 3))


tensor([[0, 1, 2],
        [3, 4, 5]])


In [22]:
print(t.reshape(3, 2))


tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [23]:
a = np.arange(6)
print(a.reshape(2, 3))


[[0 1 2]
 [3 4 5]]


In [24]:
t = torch.tensor([1, 2, 3])

print(t.shape)
print(t.unsqueeze(0).shape)  # (1, 3)
print(t.unsqueeze(1).shape)  # (3, 1)


torch.Size([3])
torch.Size([1, 3])
torch.Size([3, 1])


In [25]:
t = torch.tensor([[1, 2, 3]])

print(t.shape)
print(t.squeeze().shape)


torch.Size([1, 3])
torch.Size([3])


In [26]:
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

b = torch.tensor([10, 20, 30])

print(a + b)


tensor([[11, 22, 33],
        [14, 25, 36]])


In [27]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([10, 20, 30])

print(a + b)


[[11 22 33]
 [14 25 36]]


In [28]:
t = torch.tensor([1, 2, 3])
u = t + 1

print(t)
print(u)


tensor([1, 2, 3])
tensor([2, 3, 4])


In [29]:
t = torch.tensor([1, 2, 3])
t.add_(1)

print(t)


tensor([2, 3, 4])
